Updating code coverage and configure Code Climate
Tests for empty LDAP responses and increases the test coverage for the
User class. Uses a locally-tracked version of Code Climate's
configuration and defaults to the 'rails' setting for SimpleCov.

Only submits coverage reports to Code Climate upon a successful rspec
test run.

diff --git a/bin/ci-rspec b/bin/ci-rspec
--- a/bin/ci-rspec
+++ b/bin/ci-rspec
@@ -25,4 +25,11 @@ echo "Running RSpec with coverage reporting"
 ./${REPORTER_BIN} before-build
 bundle exec rspec
 RSPEC_EXIT_CODE=$?
-./${REPORTER_BIN} after-build
+
+if [ ${RSPEC_EXIT_CODE} -eq "0" ]; then
+  echo "Submitting coverage results to Code Climate"
+  ./${REPORTER_BIN} after-build
+else
+  echo "RSpec failed. Coverage results will not be submitted"
+  exit ${RSPEC_EXIT_CODE}
+fi
